// test_wall_qextension.cpp -- validation of the variable wall-quiescence
// extension depth (inv/qsendgame-ext, 2026-08).
//
// The feature replaces the compile-time QS_MAX_EXTRA_PLIES bound with
// three instance parameters: qsMaxExtraPlies (the old constant as
// default), plus a simple endgame rule qsLowWallsBonus /
// qsLowWallsThreshold that extends deeper when few walls remain on the
// board. Like LMR+PVS (test_lmr_pvs.cpp), the low-walls rule changes the
// search by design, so this file does not demand zero divergence between
// feature-on and feature-off runs. It validates three things:
//
//   A. Default configuration reproduces the PRE-CHANGE engine bit for
//      bit: identical score AND identical node count against frozen
//      reference values generated by tools/wallext/gen_reference.cpp from
//      the unmodified headers. This is the regression floor for the whole
//      change; any mismatch here is a bug, not instability.
//   B. Feature-on versus feature-off (default) agreement stays inside the
//      usual heuristic floors: at least 85% score agreement at equal
//      depth, at least 90% on decisive positions, and never an illegal
//      chooseMove move on the low-wall corpus.
//   C. Stack safety under stress: with aggressively raised caps in NNUE
//      mode, deep searches exercise the worst-case accumulator stack
//      (resized by the setters) without crashes, out-of-range scores, or
//      illegal moves.
//
// Build (from the repo root):
//   g++ -O2 -std=c++17 -Isrc -o bin\test_wall_qextension.exe tests\test_wall_qextension.cpp
// Run from the repo root: it loads data\nnue\nnue_weights_int8.bin.
#define QR_ENABLE_TEST_HOOKS
#include <cstdio>
#include <cstdlib>
#include <algorithm>
#include <vector>
#include "rules.hpp"
#include "search.hpp"
#include "../tools/wallext/corpus.hpp"
#include "wall_qextension_reference.inc"

using namespace qr;

static uint64_t rebuildHash(const State& s) {
    // Same construction rules as initialState()/applyMove(): pawns XOR the
    // pawn keys, walls XOR their slot keys, side to move XORs turnKey.
    Zobrist& z = zobrist();
    uint64_t h = z.pawnKey[0][s.pawn[0]] ^ z.pawnKey[1][s.pawn[1]];
    for (int i = 0; i < WS * WS; i++) {
        if ((s.wallsH >> i) & 1ull) h ^= z.wallHKey[i];
        if ((s.wallsV >> i) & 1ull) h ^= z.wallVKey[i];
    }
    if (s.turn) h ^= z.turnKey;
    return h;
}

static State stateFromRef(const wallext_ref::RefPos& rp) {
    State s;
    s.pawn[0] = (uint8_t)rp.pawn0;
    s.pawn[1] = (uint8_t)rp.pawn1;
    s.wallsH = rp.wallsH;
    s.wallsV = rp.wallsV;
    s.wallsLeft[0] = (int8_t)rp.wallsLeft0;
    s.wallsLeft[1] = (int8_t)rp.wallsLeft1;
    s.turn = rp.turn;
    s.hash = rebuildHash(s);
    return s;
}

int main(int argc, char** argv) {
    const char* weightsPath = argc > 1 ? argv[1] : "data/nnue/nnue_weights_int8.bin";
    bool ok = true;

    // ------------------------------------------------------------------
    // Part A -- exact default-config match against pre-change values.
    // ------------------------------------------------------------------
    printf("=== parte A: igualdade exata com a referencia pre-mudanca ===\n");
    int heurChecked = 0, heurOk = 0;
    int numHeurPos = (int)(sizeof(wallext_ref::REF_HEURISTIC) / sizeof(wallext_ref::REF_HEURISTIC[0]));
    for (int i = 0; i < numHeurPos; i++) {
        const auto& rv = wallext_ref::REF_HEURISTIC[i];
        State s = stateFromRef(wallext_ref::REF_POS[rv.pos]);
        Negamax eng;  // defaults: quiescence on, caps (2, 0, 0)
        SearchStats st;
        int score = eng.testFixedDepthFullWindowLmr(s, rv.depth, st);
        heurChecked++;
        if (score == rv.score && (long long)st.nodes == rv.nodes) {
            heurOk++;
        } else {
            printf("  divergencia pos=%d depth=%d: score %d vs %d esperado, nos %lld vs %lld\n",
                   rv.pos, rv.depth, score, rv.score, (long long)st.nodes, rv.nodes);
        }
    }
    printf("modo heuristico: %d/%d pares (score,nos) identicos\n", heurOk, heurChecked);
    if (heurOk != heurChecked) ok = false;

    if (!loadWeightsQuant(weightsPath)) {
        printf("FALHOU: nao carregou pesos NNUE de %s\n", weightsPath);
        return 1;
    }
    int nnueChecked = 0, nnueOk = 0;
    int numNnueVals = (int)(sizeof(wallext_ref::REF_NNUE) / sizeof(wallext_ref::REF_NNUE[0]));
    for (int i = 0; i < numNnueVals; i++) {
        const auto& rv = wallext_ref::REF_NNUE[i];
        State s = stateFromRef(wallext_ref::REF_POS[rv.pos]);
        Negamax eng;
        eng.setEvalMode(Negamax::EvalMode::NNUE);
        SearchStats st;
        int score = eng.testFixedDepthFullWindowLmr(s, rv.depth, st);
        nnueChecked++;
        if (score == rv.score && (long long)st.nodes == rv.nodes) nnueOk++;
        else printf("  divergencia NNUE pos=%d depth=%d: score %d vs %d, nos %lld vs %lld\n",
                    rv.pos, rv.depth, score, rv.score, (long long)st.nodes, rv.nodes);
    }
    printf("modo NNUE: %d/%d pares (score,nos) identicos\n", nnueOk, nnueChecked);
    if (nnueOk != nnueChecked) ok = false;

    // Setter sanity: defaults visible through the getters, and the stack
    // resize keeps covering MAX_PLY plus the worst case.
    {
        Negamax eng;
        if (eng.getQsMaxExtraPlies() != QS_MAX_EXTRA_PLIES || eng.getQsLowWallsBonus() != 0
            || eng.getQsLowWallsThreshold() != 0) {
            printf("FALHOU: defaults dos parametros errados (%d,%d,%d)\n",
                   eng.getQsMaxExtraPlies(), eng.getQsLowWallsBonus(), eng.getQsLowWallsThreshold());
            ok = false;
        }
        eng.setQsLowWallsBonus(6);
        eng.setQsMaxExtraPlies(6);
        // Deep NNUE search must survive after the resizes above.
        State s = stateFromRef(wallext_ref::REF_POS[0]);
        eng.setEvalMode(Negamax::EvalMode::NNUE);
        SearchStats st;
        int score = eng.testFixedDepthFullWindowLmr(s, 10, st);
        if (score <= -SCORE_INF || score >= SCORE_INF || st.nodes == 0) {
            printf("FALHOU: busca NNUE apos resize devolveu score fora do intervalo (%d)\n", score);
            ok = false;
        }
    }

    std::vector<wallext::CorpusEntry> corpus = wallext::buildCorpus();
    printf("corpus: %zu posicoes\n", corpus.size());
    if (corpus.size() < 300) {
        printf("FALHOU: corpus pequeno demais (%zu < 300)\n", corpus.size());
        ok = false;
    }

    // ------------------------------------------------------------------
    // Part B -- agreement of the low-walls rule with the default engine.
    // ------------------------------------------------------------------
    printf("=== parte B: concordancia regra ligada vs default ===\n");
    struct Variant { int bonus; int threshold; };
    const Variant VARIANTS[] = {{1, 4}, {2, 6}, {3, 2}};
    const int AGREEMENT_DEPTH = 6;
    const int STRIDE = 6;             // ~1/6 of the corpus per variant run
    const int DECISIVE_THRESHOLD = 5; // heuristic eval scale in these endgames is small

    int totalIllegal = 0;
    int variantIndex = 0;
    for (const Variant& v : VARIANTS) {
        int checked = 0, matches = 0, decChecked = 0, decMatches = 0;
        long long nodesBase = 0, nodesVar = 0;
        // Different phase per variant so the three runs cover the corpus
        // broadly without tripling the runtime of any single slice.
        for (size_t i = (size_t)variantIndex; i < corpus.size(); i += STRIDE) {
            const State& s = corpus[i].s;
            if (s.wallsLeft[0] + s.wallsLeft[1] > v.threshold + 2) continue;
            Negamax baseEng;
            SearchStats stBase;
            int baseScore = baseEng.testFixedDepthFullWindowLmr(s, AGREEMENT_DEPTH, stBase);

            Negamax varEng;
            varEng.setQsLowWallsBonus(v.bonus);
            varEng.setQsLowWallsThreshold(v.threshold);
            SearchStats stVar;
            int varScore = varEng.testFixedDepthFullWindowLmr(s, AGREEMENT_DEPTH, stVar);

            checked++;
            nodesBase += stBase.nodes;
            nodesVar += stVar.nodes;
            if (varScore == baseScore) matches++;
            if (std::abs(baseScore) >= DECISIVE_THRESHOLD) {
                decChecked++;
                if (varScore == baseScore) decMatches++;
            }

            // Production-path legality check with the rule enabled.
            Negamax prodEng;
            prodEng.setQsLowWallsBonus(v.bonus);
            prodEng.setQsLowWallsThreshold(v.threshold);
            SearchStats stChoose;
            Move mv = prodEng.chooseMove(s, AGREEMENT_DEPTH, 600000, stChoose);
            qr::MoveList legal = qr::legalMoves(s);
            if (std::find(legal.begin(), legal.end(), mv) == legal.end()) {
                totalIllegal++;
                printf("FALHOU: lance ilegal (bonus=%d thr=%d) na posicao %zu\n",
                       v.bonus, v.threshold, i);
                ok = false;
            }
        }
        double agreePct = checked ? 100.0 * matches / checked : 100.0;
        double decPct = decChecked ? 100.0 * decMatches / decChecked : 100.0;
        printf("bonus=%d thr=%d: concordancia %d/%d (%.1f%%), decisivas %d/%d (%.1f%%), "
               "nos %.2fx vs default\n",
               v.bonus, v.threshold, matches, checked, agreePct,
               decMatches, decChecked, decPct,
               nodesBase ? (double)nodesVar / (double)nodesBase : 0.0);
        if (agreePct < 85.0) { printf("FALHOU: concordancia abaixo do piso de 85%%\n"); ok = false; }
        if (decPct < 90.0) { printf("FALHOU: concordancia decisiva abaixo do piso de 90%%\n"); ok = false; }
        variantIndex++;
    }

    // ------------------------------------------------------------------
    // Part C -- NNUE stack stress with aggressive caps.
    // ------------------------------------------------------------------
    printf("=== parte C: estresse da pilha de acumuladores (NNUE) ===\n");
    {
        // Resize contract: default capacity covers MAX_PLY + (2 + 0) + 4;
        // raising the caps must grow it by the same amount. This, plus the
        // defensive clamp inside quiescence(), is what keeps curAcc+1 in
        // bounds; there is no ASAN on this toolchain to catch a violation
        // after the fact.
        Negamax capCheck;
        if (capCheck.testNnueAccStackCapacity() != (size_t)(MAX_PLY + QS_MAX_EXTRA_PLIES + 4)) {
            printf("FALHOU: capacidade default da pilha errada (%zu)\n",
                   capCheck.testNnueAccStackCapacity());
            ok = false;
        }
        capCheck.setQsMaxExtraPlies(6);
        capCheck.setQsLowWallsBonus(6);
        size_t want = (size_t)MAX_PLY + 6 + 6 + 4;
        if (capCheck.testNnueAccStackCapacity() != want) {
            printf("FALHOU: resize da pilha nao acompanhou os caps (%zu vs %zu)\n",
                   capCheck.testNnueAccStackCapacity(), want);
            ok = false;
        }

        Negamax stress;
        stress.setEvalMode(Negamax::EvalMode::NNUE);
        stress.setQsMaxExtraPlies(6);
        stress.setQsLowWallsBonus(6);
        stress.setQsLowWallsThreshold(20);  // bonus applies everywhere
        int stressed = 0;
        for (size_t i = 0; i < corpus.size(); i += corpus.size() / 6) {
            const State& s = corpus[corpus.size() - 1 - i].s;  // lowest walls last
            SearchStats st;
            int score = stress.testFixedDepthFullWindowLmr(s, 12, st);
            stressed++;
            if (score <= -SCORE_INF || score >= SCORE_INF) {
                printf("FALHOU: score fora do intervalo na posicao %zu (profunda)\n",
                       corpus.size() - 1 - i);
                ok = false;
            }
            SearchStats stChoose;
            Move mv = stress.chooseMove(s, 10, 600000, stChoose);
            qr::MoveList legal = qr::legalMoves(s);
            if (std::find(legal.begin(), legal.end(), mv) == legal.end()) {
                totalIllegal++;
                printf("FALHOU: lance ilegal NNUE profundo na posicao %zu\n", corpus.size() - 1 - i);
                ok = false;
            }
        }
        printf("estresse: %d buscas profundas (caps 6+6, thr=20) sem crash, lances ilegais=%d\n",
               stressed, totalIllegal);
    }

    if (totalIllegal > 0) ok = false;

    if (ok) {
        printf("OK -- extensao de quiescencia variavel dentro de todos os pisos\n");
        return 0;
    }
    printf("FALHOU -- veja as linhas acima\n");
    return 1;
}
