// gen_reference.cpp -- generates tests/wall_qextension_reference.inc,
// the frozen expected values used by tests/test_wall_qextension.cpp.
//
// Run this BEFORE changing src/search.hpp, from the repo root:
//   g++ -O2 -std=c++17 -Isrc -o bin\gen_reference.exe tools\wallext\gen_reference.cpp
//   bin\gen_reference.exe > tests\wall_qextension_reference.inc
//
// The generator searches a fixed slice of the corpus with the production
// configuration of the CURRENT (pre-change) headers and records score and
// node count per (position, depth) pair. The correctness test replays the
// same searches after the change and demands an exact match, which proves
// that the new instance parameters reproduce the old behavior bit for bit
// when left at their defaults. Compile with -O2 and without
// -march=native/-mavx2 so floating-point eval paths stay reproducible.
//
// Determinism rests on testFixedDepthFullWindowLmr: it resets the TT and
// the ordering state, uses a full window, and sets an unlimited race
// solver budget, so every value here is a pure function of the position
// and the depth.
#define QR_ENABLE_TEST_HOOKS
#include <cstdio>
#include <cstdint>
#include <vector>
#include "corpus.hpp"
#include "search.hpp"

using namespace qr;
using namespace wallext;
using std::vector;

static uint64_t rebuildHash(const State& s) {
    // Same construction rules as initialState()/applyMove(): pawns XOR the
    // pawn keys, walls XOR their slot keys, side to move XORs turnKey.
    Zobrist& z = zobrist();
    uint64_t h = z.pawnKey[0][s.pawn[0]] ^ z.pawnKey[1][s.pawn[1]];
    for (int i = 0; i < WS * WS; i++) {
        if ((s.wallsH >> i) & 1ull) h ^= z.wallHKey[i];
        if ((s.wallsV >> i) & 1ull) h ^= z.wallVKey[i];
    }
    if (s.turn) h ^= z.turnKey;
    return h;
}

int main(int argc, char** argv) {
    const char* weightsPath = argc > 1 ? argv[1] : "data/nnue/nnue_weights_int8.bin";

    std::vector<CorpusEntry> corpus = buildCorpus();
    printf("// wall_qextension_reference.inc -- frozen expected values for\n");
    printf("// tests/test_wall_qextension.cpp. Generated by\n");
    printf("// tools/wallext/gen_reference.cpp against the PRE-CHANGE headers\n");
    printf("// (inv/qsendgame-ext base commit). DO NOT EDIT BY HAND.\n");
    printf("\n");
    printf("namespace wallext_ref {\n\n");
    printf("struct RefPos { unsigned pawn0, pawn1; unsigned long long wallsH, wallsV;\n");
    printf("               int wallsLeft0, wallsLeft1, turn; };\n");
    printf("struct RefVal { int pos; int depth; long long nodes; int score; };\n\n");

    // ---- Heuristic-mode reference slice: first 3 entries per bucket ----
    std::vector<int> refIdx;
    {
        int lastTotal = -999, perBucket = 0;
        for (int i = 0; i < (int)corpus.size(); i++) {
            int total = corpus[i].s.wallsLeft[0] + corpus[i].s.wallsLeft[1];
            if (total != lastTotal) { lastTotal = total; perBucket = 0; }
            if (perBucket < 3) { refIdx.push_back(i); perBucket++; }
        }
    }

    printf("static const RefPos REF_POS[] = {\n");
    for (int idx : refIdx) {
        const State& s = corpus[idx].s;
        printf("    {%uu,%uu,%uull,%uull,%d,%d,%d},\n",
               (unsigned)s.pawn[0], (unsigned)s.pawn[1],
               (unsigned long long)s.wallsH, (unsigned long long)s.wallsV,
               (int)s.wallsLeft[0], (int)s.wallsLeft[1], (int)s.turn);
    }
    // Hash sanity: rebuilt hashes must match the corpus hashes.
    for (int idx : refIdx) {
        State s = corpus[idx].s;
        if (rebuildHash(s) != s.hash) {
            fprintf(stderr, "FATAL: hash rebuild mismatch at corpus index %d\n", idx);
            return 1;
        }
    }

    // ---- NNUE-mode positions: appended to REF_POS after the slice above,
    // so both tables share one position array. Lowest-wall positions come
    // last in the corpus, hence the backward scan.
    if (!loadWeightsQuant(weightsPath)) {
        fprintf(stderr, "FATAL: cannot load NNUE weights from %s\n", weightsPath);
        return 1;
    }
    std::vector<int> nnueIdx;
    {
        int lastTotal = -999, perBucket = 0;
        for (int i = (int)corpus.size() - 1; i >= 0 && (int)nnueIdx.size() < 4; i--) {
            int total = corpus[i].s.wallsLeft[0] + corpus[i].s.wallsLeft[1];
            if (total != lastTotal) { lastTotal = total; perBucket = 0; }
            bool dupAgainstSlice = false;
            for (int r : refIdx) {
                if (r == i) { dupAgainstSlice = true; break; }
            }
            if (!dupAgainstSlice && perBucket < 2) { nnueIdx.push_back(i); perBucket++; }
        }
    }
    int nnueBase = (int)refIdx.size();
    for (int idx : nnueIdx) {
        const State& s = corpus[idx].s;
        printf("    {%uu,%uu,%uull,%uull,%d,%d,%d},\n",
               (unsigned)s.pawn[0], (unsigned)s.pawn[1],
               (unsigned long long)s.wallsH, (unsigned long long)s.wallsV,
               (int)s.wallsLeft[0], (int)s.wallsLeft[1], (int)s.turn);
    }
    printf("};\n\n");

    // ---- Heuristic mode: depths 4..8 on every reference position ----
    const int HEUR_DEPTHS[] = {4, 5, 6, 7, 8};
    printf("static const RefVal REF_HEURISTIC[] = {\n");
    for (int k = 0; k < (int)refIdx.size(); k++) {
        State s = corpus[refIdx[k]].s;
        for (int depth : HEUR_DEPTHS) {
            Negamax eng;
            SearchStats st;
            int score = eng.testFixedDepthFullWindowLmr(s, depth, st);
            printf("    {%d,%d,%lldll,%d},\n", k, depth, (long long)st.nodes, score);
        }
        fflush(stdout);
    }
    printf("};\n\n");

    // ---- NNUE mode: deep searches on the lowest-wall positions ----
    // These pin the incremental accumulator stack behavior at extension
    // depths far beyond the default cap.
    const int NNUE_DEPTHS[] = {10, 12};
    printf("static const RefVal REF_NNUE[] = {\n");
    for (int k = 0; k < (int)nnueIdx.size(); k++) {
        State s = corpus[nnueIdx[k]].s;
        fprintf(stderr, "NNUE ref: corpus idx %d, total walls %d\n", nnueIdx[k],
                (int)(s.wallsLeft[0] + s.wallsLeft[1]));
        for (int depth : NNUE_DEPTHS) {
            Negamax eng;
            eng.setEvalMode(Negamax::EvalMode::NNUE);
            SearchStats st;
            int score = eng.testFixedDepthFullWindowLmr(s, depth, st);
            printf("    {%d,%d,%lldll,%d},\n", nnueBase + k, depth, (long long)st.nodes, score);
        }
        fflush(stdout);
    }
    printf("};\n\n");
    printf("} // namespace wallext_ref\n");

    fprintf(stderr, "corpus=%zu ref positions=%zu nnue positions=%zu\n",
            corpus.size(), refIdx.size(), nnueIdx.size());
    return 0;
}
